/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 */
package org.netbeans.modules.php.wordpress.ui.wizards;

import javax.swing.JPanel;

/**
 *
 * @author junichi11
 */
public class WpConfigPanel extends JPanel {

    private static final long serialVersionUID = -3971880529277616096L;

    // keep values
    // restore values if the cancel button is clicked
    private String dbName = ""; // NOI18N
    private String dbUser = ""; // NOI18N
    private String dbPassword = ""; // NOI18N
    private String dbHost = "localhost"; // NOI18N
    private String dbCharset = "utf8"; // NOI18N
    private String dbCollate = ""; // NOI18N

    /**
     * Creates new form WpConfigPanel
     */
    public WpConfigPanel() {
        initComponents();
    }

    public String getDbName() {
        return dbNameTextField.getText().trim();
    }

    void setDbName(String dbName) {
        dbNameTextField.setText(dbName);
    }

    public String getDbUser() {
        return dbUserTextField.getText().trim();
    }

    void setDbUser(String dbUser) {
        dbUserTextField.setText(dbUser);
    }

    public String getDbPassword() {
        return dbPasswordTextField.getText().trim();
    }

    void setDbPassword(String dbPassword) {
        dbPasswordTextField.setText(dbPassword);
    }

    public String getDbHost() {
        return dbHostTextField.getText().trim();
    }

    void setDbHost(String dbHost) {
        dbHostTextField.setText(dbHost);
    }

    public String getDbCharset() {
        return dbCharsetTextField.getText().trim();
    }

    void setDbCharset(String dbCharset) {
        dbCharsetTextField.setText(dbCharset);
    }

    public String getDbCollate() {
        return dbCollateTextField.getText().trim();
    }

    void setDbCollate(String dbCollate) {
        dbCollateTextField.setText(dbCollate);
    }

    void store() {
        dbName = getDbName();
        dbUser = getDbUser();
        dbPassword = getDbPassword();
        dbHost = getDbHost();
        dbCharset = getDbCharset();
        dbCollate = getDbCollate();
    }

    void restore() {
        setDbName(dbName);
        setDbUser(dbUser);
        setDbPassword(dbPassword);
        setDbHost(dbHost);
        setDbCharset(dbCharset);
        setDbCollate(dbCollate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbUserTextField = new javax.swing.JTextField();
        dbPasswordLabel = new javax.swing.JLabel();
        dbHostLabel = new javax.swing.JLabel();
        dbCharsetLabel = new javax.swing.JLabel();
        dbCollateLabel = new javax.swing.JLabel();
        dbPasswordTextField = new javax.swing.JTextField();
        dbHostTextField = new javax.swing.JTextField();
        dbCharsetTextField = new javax.swing.JTextField();
        dbNameLabel = new javax.swing.JLabel();
        dbCollateTextField = new javax.swing.JTextField();
        dbNameTextField = new javax.swing.JTextField();
        dbUserLabel = new javax.swing.JLabel();

        dbUserTextField.setText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbUserTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbPasswordLabel, org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbPasswordLabel.text")); // NOI18N
        dbPasswordLabel.setToolTipText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbPasswordLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbHostLabel, org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbHostLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbCharsetLabel, org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbCharsetLabel.text")); // NOI18N
        dbCharsetLabel.setToolTipText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbCharsetLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbCollateLabel, org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbCollateLabel.text")); // NOI18N
        dbCollateLabel.setToolTipText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbCollateLabel.toolTipText")); // NOI18N

        dbPasswordTextField.setText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbPasswordTextField.text")); // NOI18N

        dbHostTextField.setText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbHostTextField.text")); // NOI18N

        dbCharsetTextField.setText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbCharsetTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbNameLabel, org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbNameLabel.text")); // NOI18N

        dbCollateTextField.setText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbCollateTextField.text")); // NOI18N

        dbNameTextField.setText(org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbUserLabel, org.openide.util.NbBundle.getMessage(WpConfigPanel.class, "WpConfigPanel.dbUserLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbNameLabel)
                    .addComponent(dbHostLabel)
                    .addComponent(dbCharsetLabel)
                    .addComponent(dbCollateLabel)
                    .addComponent(dbUserLabel)
                    .addComponent(dbPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dbUserTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dbPasswordTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dbHostTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(dbCharsetTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dbCollateTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbNameLabel)
                    .addComponent(dbNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUserLabel)
                    .addComponent(dbUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbPasswordLabel)
                    .addComponent(dbPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbHostLabel)
                    .addComponent(dbHostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbCharsetLabel)
                    .addComponent(dbCharsetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbCollateLabel)
                    .addComponent(dbCollateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbCharsetLabel;
    private javax.swing.JTextField dbCharsetTextField;
    private javax.swing.JLabel dbCollateLabel;
    private javax.swing.JTextField dbCollateTextField;
    private javax.swing.JLabel dbHostLabel;
    private javax.swing.JTextField dbHostTextField;
    private javax.swing.JLabel dbNameLabel;
    private javax.swing.JTextField dbNameTextField;
    private javax.swing.JLabel dbPasswordLabel;
    private javax.swing.JTextField dbPasswordTextField;
    private javax.swing.JLabel dbUserLabel;
    private javax.swing.JTextField dbUserTextField;
    // End of variables declaration//GEN-END:variables
}
